// <auto-generated />
namespace AskYourMechanicDon.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class datetimeOffOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datetimeOffOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201802230238201_datetimeOffOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
