// <auto-generated />
namespace AskYourMechanicDon.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class orderitemcustomer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderitemcustomer));
        
        string IMigrationMetadata.Id
        {
            get { return "201801181646493_orderitemcustomer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
