// <auto-generated />
namespace AskYourMechanicDon.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class datetimeOffsetOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datetimeOffsetOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201802230222098_datetimeOffsetOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
